### PR TITLE
Add specs for custom model custom method

### LINKED ISSUE #89: Failure to recurse models in custom methods
We have the possibility of recursive elements in models. That works:

````
require "lutaml/model"
require 'lutaml/model/xml_adapter/nokogiri_adapter'

Lutaml::Model::Config.configure do |config|
  config.xml_adapter = Lutaml::Model::XmlAdapter::NokogiriAdapter
end

module SimpleModel
  class Address < Lutaml::Model::Serializable
    attribute :street, :string
    attribute :city, :string
    attribute :address, Address

    xml do
      root "address"
      map_element "street", to: :street
      map_element "city", to: :city
      map_element "address", to: :address
    end
  end

  xml = <<~XML
  <address>
  <street>A</street>
  <city>B</city>
  <address>
  <street>C</street>
  <city>D</city>
  </address>
  </address>
  XML

  sample = SimpleModel::Address.from_xml(xml)
  pp sample.to_xml
end

 "<address>\n" +
"  <street>A</street>\n" +
"  <city>B</city>\n" +
"  <address>\n" +
"    <street>C</street>\n" +
"    <city>D</city>\n" +
"  </address>\n" +
"</address>"
````

Now, I can always use a custom method for XML.

````
module SimpleModel
  class Address < Lutaml::Model::Serializable
    attribute :street, :string
    attribute :city, :string
    attribute :address, Address

    xml do
      root "address"
      map_element "street", to: :street
      map_element "city", to: :city, with: { from: :city_from_xml, to: :city_to_xml }
      map_element "address", to: :address
    end

    def city_from_xml(model, node)
      model.city = node
    end

    def city_to_xml(model, parent, doc)
      doc.add_element(parent, "<city>#{model.city}</city>")
    end
  end
````

If I pass that

````
  xml = <<~XML
  <address>
  <street>A</street>
  <city>B</city>
  </address>
  XML
````

I get the same XML back out.

But if I pass it:

````
  xml = <<~XML
  <address>
  <street>A</street>
  <city>B</city>
  <address>
  <street>C</street>
  <city>D</city>
  </address>
  </address>
  XML
````

I get back:

````
  xml = <<~XML
  <address>
  <street>A</street>
  <city>B</city>
  <address>
  <street>C</street>
  <city>B</city>  <=== BZZZT
  </address>
  </address>
  XML
````

And that is because

````
  def city_to_xml(model, parent, doc)
      doc.add_element(parent, "<city>#{model.city}</city>")
    end
````

when called recursively for address/address, does NOT update the value of `model` to address/address: it stays at the top level of address.

That means that recursive data definitions + custom methods fail. This is an issue for me with Metanorma collection manifests https://github.com/metanorma/metanorma/issues/401 , which are recursive, and can contain Relaton data, with the Relaton data rendered in a custom method.

This I gather from @andrew2net is broken in Shale as well: the custom method model doesn't cope with recursion, because recursion is unusual in toy models. But this really is simply a bug: if I call city_to_xml when processing address/address, I expect model in city_to_xml to be address/address, not address. And of course that needs to work at arbitrary depth of recursion.

### PR DESCRIPTION
**Pull request by ronaldtse**
This is meant to provide specs for the fix of:
* #83 

@HassanAkbar can you help add your fixes here? The specs are only for demonstration, they will need to be cleaned/fixed. Thanks! 

fixes #89

### CODE REVIEW

**Comment by ronaldtse** [comment]
@HassanAkbar can you please help modify this PR for the newly addressed #86 ? 

Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse Sure, I'm looking into it

**Comment by HassanAkbar** [comment]
@ronaldtse This has been finalized by me. Can you review this? Thanks

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar ! LGTM. Can you please help rebase and merge?

**Pull request merged**
