### PR TITLE
feat: add map_all for xml mapping

### LINKED ISSUE #57: (URGENT) Mixed content at root not working
I'm trying to use the mixed content option to parse the XML:
```xml
<docidentifier type="BIPM" scope="part" primary="true">CIPM 43<sup>e</sup> réunion (1950)</docidentifier>
```
The class:
```ruby
module Relaton
  module Model
    class Docidentifier < Lutaml::Model::Serializable

      attribute :type, Lutaml::Model::Type::String
      attribute :scope, Lutaml::Model::Type::String
      attribute :primary, Lutaml::Model::Type::Boolean
      attribute :sup, Lutaml::Model::Type::String

      xml do
        root "docidentifier", mixed: true
        map_element "sup", to: :sup
        map_attribute "type", to: :type
        map_attribute "scope", to: :scope
        map_attribute "primary", to: :primary
      end
    end
  end
end
```
The result:
```ruby
> docid = Relaton::Model::Docidentifier.from_xml xml
#class = Relaton::Model::Docidentifier
@element_order = ["text", :sup, "text"]
@ordered = true
@primary = true
@scope = "part"
@sup = "e"
@type = "BIPM"

> docid.to_xml
"<docidentifier type=\"BIPM\" scope=\"part\" primary=\"true\">\n" + "  <sup>e</sup>\n" + "</docidentifier>"
```
The text content disappears. What is wrong here?

### PR DESCRIPTION
**Pull request by HassanAkbar**
Added `map_all` for mapping all content inside an XML tag to an attribute.

fixes #57 
can be used for -> https://github.com/lutaml/lutaml-model/issues/106

### CODE REVIEW

**Review by ronaldtse — CHANGES_REQUESTED** [review]
@HassanAkbar looks good! Could you please help document this in the README with an example? Thanks.

**Comment by ronaldtse** [comment]
@HassanAkbar what happens with map_all when the format is JSON? Does this mean that a class that uses map_all cannot do JSON etc?

**Comment by HassanAkbar** [comment]
@ronaldtse Yes this PR only adds `map_all` for XML mappings, For JSON we do not need the `map_all` method because our internal representation is hash and we can map an attribute to a string, something like below and it will work

```ruby
person = { 
  name: "test", 
  age: "20", 
  description: { title: "foobar", awards: "many" }
}.to_json

class Person < Lutaml::Model::Serializable
  attribute :name, :string
  attribute :age, :integer
  attribute :description, :string
  
  json do
    map "name", to: :name
    map "age", to: :age
    map "description", to: :description
  end
end

Person.from_json(person)
#<Person:0x00000001044dd9b0                                     
 @age=20,                                                       
 @description="{\"title\"=>\"foobar\", \"awards\"=>\"many\"}",  
 @name="test",                                                  
 @using_default={:name=>false, :age=>false, :description=>false},
 @validate_on_set=false> 
```

I will open a separate branch for `YAML` and `toml`. 
I added this only in a separate PR because this was marked urgent and has been in progress for a long time.

**Comment by ronaldtse** [comment]
I think what I don't understand is, how does the concept of `map_all` work with JSON, YAML and TOML?

JSON is like: `{ "attr" : "value" }`. Does that mean map_all will give the raw value of `{ "attr" : "value" }`?

YAML is like: `attr: value`. Does that mean map_all will give the raw value?

Does `map_all` on this element produce:

```xml
<element>
  <one>text</one>
</element>
```

1. The entire element?

```xml
<element attr=1>
  <one>text</one>
</element>
```

2. Only the inner content of the element?

```xml
  <one>text</one>
```

**Comment by HassanAkbar** [comment]
@ronaldtse the `map_all` will work by assigning everything inside the tag or the key it is defined in. for example

- ### For `XML`
  `map_all` will assign all the content inside that tag but will not assign the attributes in the current tag. i.e
  
  ```ruby
  class Element < Lutaml::Model::Serializable
    attribute :all_content, :string
    
    xml do
      map_all to: :all_content
    end
  end
  ```
  ```xml
  <element attr1="1">
    <one attr2="2" attr3="3">text</one>
  </element>
  ```
  ```ruby
  Element.from_xml(xml).all_content
  > "<one attr2=\"2\" attr3=\"3\">text</one>"
  ```

- ### For `YAML`, `JSON`, and `TOML`
  `map_all` will assign all the content against the key to the model attribute. i.e

  ```ruby
  class Element < Lutaml::Model::Serializable
    attribute :all_content, :string
    
    yaml do
      map_all to: :all_content
    end
    
    json do
      map_all to: :all_content
    end

    toml do
      map_all to: :all_content
    end
  end
  ```

  **YAML Example**

  ```yaml
  element:
  - another_element
  - element_with_childs
    name: "John"
  ```
  ```ruby
  Element.from_yaml(yaml).all_content
  > "- another_element\n- element_with_childs\n  name: \"John\""
  ```

  **JSON Example**

  ```json
  { 
    "element": [
      "another_element",
      "element_with_childs": { "name": "John" }
    ]
  }
  ```
  ```ruby
  Element.from_json(json).all_content
  > "[\"another_element\", \"element_with_childs\": {\"name\": \"John\"}]"
  ```

**Pull request merged**
