### PR TITLE
feat: improved data type handling

### PR DESCRIPTION
**Pull request by ronaldtse**
This is WIP.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Current spec failures:

```
  1) Lutaml::Model::Attribute#cast_type raises ArgumentError on unknown type
     Failure/Error:
       expect { name_attr.cast_type(:foobar) }
         .to raise_error(ArgumentError, "Unknown Lutaml::Model::Type: foobar")
     
       expected ArgumentError with "Unknown Lutaml::Model::Type: foobar", got #<TypeError: Invalid type: foobar> with backtrace:
         # ./lib/lutaml/model/attribute.rb:44:in `rescue in cast_type'
         # ./lib/lutaml/model/attribute.rb:32:in `cast_type'
         # ./spec/lutaml/model/attribute_spec.rb:46:in `block (4 levels) in <top (required)>'
         # ./spec/lutaml/model/attribute_spec.rb:46:in `block (3 levels) in <top (required)>'
     # ./spec/lutaml/model/attribute_spec.rb:46:in `block (3 levels) in <top (required)>'

  2) Lutaml::Model::Type Type System .register and .lookup with invalid types raises TypeError when registering non-Type::Value class
     Failure/Error: expect { described_class.register(:invalid, InvalidType) }.to raise_error(Lutaml::Model::TypeError, /not a valid Lutaml::Model::Type::Value/)
     
     NameError:
       uninitialized constant Lutaml::Model::TypeError
     # ./spec/lutaml/model/type_spec.rb:42:in `block (5 levels) in <top (required)>'

  3) Lutaml::Model::Type Type System Built-in Types has all built-in types registered
     Failure/Error: raise UnknownTypeError.new(type_name) unless klass
     
     Lutaml::Model::UnknownTypeError:
       Unknown type 'string'
     # ./lib/lutaml/model/type.rb:21:in `lookup'
     # ./spec/lutaml/model/type_spec.rb:68:in `block (5 levels) in <top (required)>'
     # ./spec/lutaml/model/type_spec.rb:67:in `each'
     # ./spec/lutaml/model/type_spec.rb:67:in `block (4 levels) in <top (required)>'

  4) Lutaml::Model::Type Type System Decimal Type when BigDecimal is available registers and uses Decimal type
     Failure/Error: raise UnknownTypeError.new(type_name) unless klass
     
     Lutaml::Model::UnknownTypeError:
       Unknown type 'decimal'
     # ./lib/lutaml/model/type.rb:21:in `lookup'
     # ./spec/lutaml/model/type_spec.rb:112:in `block (5 levels) in <top (required)>'

  5) Lutaml::Model::Type Type Usage in Models Serialization correctly serializes to XML
     Failure/Error:
       public_send(element_name, attributes) do
         xml.parent.namespace = nil if prefix.nil? && !prefix_unset
         yield(self)
       end
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `hash'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `public_send'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `create_and_add_element'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:156:in `add_to_xml'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:221:in `block (2 levels) in build_unordered_element'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:209:in `each'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:209:in `block in build_unordered_element'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:45:in `block in create_and_add_element'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:68:in `public_send'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:68:in `method_missing'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `public_send'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `create_and_add_element'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:199:in `build_unordered_element'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:122:in `build_element'
     # ./lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:23:in `block in to_xml'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:9:in `block in build'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:8:in `new'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:8:in `build'
     # ./lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:16:in `to_xml'
     # ./lib/lutaml/model/serialize.rb:528:in `public_send'
     # ./lib/lutaml/model/serialize.rb:528:in `block (2 levels) in <module:Serialize>'
     # ./spec/lutaml/model/type_spec.rb:215:in `block (4 levels) in <top (required)>'

  6) Person deserializes from XML
     Failure/Error: expect(person.wakeup_time).to eq(Time.parse("07:00:00"))
     
       expected: 2024-10-30 07:00:00.000000000 +0800
            got: 0001-01-01 07:00:00.000000000 +0800
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -2024-10-30 07:00:00 +0800
       +0001-01-01 07:00:00 +0800
       
     # ./spec/person_spec.rb:82:in `block (2 levels) in <top (required)>'

  7) Person deserializes from JSON
     Failure/Error: expect(person.wakeup_time).to eq(Time.parse("07:00:00"))
     
       expected: 2024-10-30 07:00:00.000000000 +0800
            got: 0001-01-01 07:00:00.000000000 +0800
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -2024-10-30 07:00:00 +0800
       +0001-01-01 07:00:00 +0800
       
     # ./spec/person_spec.rb:98:in `block (2 levels) in <top (required)>'

  8) Person deserializes from JSON array
     Failure/Error: expect(persons[0].wakeup_time).to eq(Time.parse("07:00:00"))
     
       expected: 2024-10-30 07:00:00.000000000 +0800
            got: 0001-01-01 07:00:00.000000000 +0800
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -2024-10-30 07:00:00 +0800
       +0001-01-01 07:00:00 +0800
       
     # ./spec/person_spec.rb:112:in `block (2 levels) in <top (required)>'

  9) Person deserializes from YAML
     Failure/Error: expect(person.wakeup_time).to eq(Time.parse("07:00:00"))
     
       expected: 2024-10-30 07:00:00.000000000 +0800
            got: 0001-01-01 07:00:00.000000000 +0800
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -2024-10-30 07:00:00 +0800
       +0001-01-01 07:00:00 +0800
       
     # ./spec/person_spec.rb:136:in `block (2 levels) in <top (required)>'

  10) Person deserializes from YAML array
      Failure/Error: expect(persons[0].wakeup_time).to eq(Time.parse("07:00:00"))
      
        expected: 2024-10-30 07:00:00.000000000 +0800
             got: 0001-01-01 07:00:00.000000000 +0800
      
        (compared using ==)
      
        Diff:
        @@ -1 +1 @@
        -2024-10-30 07:00:00 +0800
        +0001-01-01 07:00:00 +0800
        
      # ./spec/person_spec.rb:150:in `block (2 levels) in <top (required)>'

Finished in 0.09417 seconds (files took 0.27243 seconds to load)
345 examples, 10 failures, 36 pending
```

**Comment by ronaldtse** [comment]
@HassanAkbar can you help with completing this?

There is one lingering question: what do we do with the "Time" or "TimeWithoutDate" type? How do we represent it in Ruby? The default "Time" class also handles a date, so either we have to implement our own "time without date" class... or hack the "Time" class to ignore date?

**Comment by HassanAkbar** [comment]
@ronaldtse I'm looking into it.

> There is one lingering question: what do we do with the "Time" or "TimeWithoutDate" type? How do we represent it in Ruby? The default "Time" class also handles a date, so either we have to implement our own "time without date" class... or hack the "Time" class to ignore date?

I think we should implement our own `TimeWithoutDate ` class that inherits from the time class or has a time object internally to manage the time.

**Comment by ronaldtse** [comment]
All specs fixed.

**Comment by ronaldtse** [comment]
Additional failures to be fixed... 

```
  1) Lutaml::Model::Type::Date.cast with DateTime object is expected to eq #<Date: 2024-01-01 ((2460311j,0s,0n),+0s,2299161j)>
     Failure/Error: it { is_expected.to eq(Date.new(2024, 1, 1)) }
     
       expected: #<Date: 2024-01-01 ((2460311j,0s,0n),+0s,2299161j)>
            got: #<DateTime: 2024-01-01T12:00:00+00:00 ((2460311j,43200s,0n),+0s,2299161j)>
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -#<Date: 2024-01-01 ((2460311j,0s,0n),+0s,2299161j)>
       +#<DateTime: 2024-01-01T12:00:00+00:00 ((2460311j,43200s,0n),+0s,2299161j)>
       
     # ./spec/lutaml/model/type/date_spec.rb:28:in `block (4 levels) in <top (required)>'

  2) Lutaml::Model::Type::Hash.cast filters out text keys from nested hashes
     Failure/Error: expect(described_class.cast(hash)).to eq expected
     
       expected: {"key1"=>{"other"=>"value1"}, "key2"=>{"other"=>"value2"}}
            got: {"key1"=>{"other"=>"value1", "text"=>"content1"}, "key2"=>{"other"=>"value2", "text"=>"content2"}}
     
       (compared using ==)
     
       Diff:
       @@ -1,3 +1,3 @@
       -"key1" => {"other"=>"value1"},
       -"key2" => {"other"=>"value2"},
       +"key1" => {"other"=>"value1", "text"=>"content1"},
       +"key2" => {"other"=>"value2", "text"=>"content2"},
       
     # ./spec/lutaml/model/type/hash_spec.rb:35:in `block (3 levels) in <top (required)>'

  3) Lutaml::Model::Type::Integer.cast with float string is expected to eq 123
     Failure/Error: it { is_expected.to eq(123) }
     
       expected: 123
            got: nil
     
       (compared using ==)
     # ./spec/lutaml/model/type/integer_spec.rb:40:in `block (4 levels) in <top (required)>'

  4) Lutaml::Model::Type::Integer.cast with exponential notation is expected to eq 123
     Failure/Error: it { is_expected.to eq(123) }
     
       expected: 123
            got: nil
     
       (compared using ==)
     # ./spec/lutaml/model/type/integer_spec.rb:46:in `block (4 levels) in <top (required)>'

  5) Lutaml::Model::Type::Integer.cast with negative exponential notation is expected to eq -123
     Failure/Error: it { is_expected.to eq(-123) }
     
       expected: -123
            got: nil
     
       (compared using ==)
     # ./spec/lutaml/model/type/integer_spec.rb:52:in `block (4 levels) in <top (required)>'

  6) Lutaml::Model::Type::Integer.cast with string containing leading zeros is expected to eq 123
     Failure/Error: it { is_expected.to eq(123) }
     
       expected: 123
            got: 83
     
       (compared using ==)
     # ./spec/lutaml/model/type/integer_spec.rb:58:in `block (4 levels) in <top (required)>'

  7) Lutaml::Model::Type Type Usage in Models Serialization correctly serializes to XML
     Failure/Error:
       public_send(element_name, attributes) do
         xml.parent.namespace = nil if prefix.nil? && !prefix_unset
         yield(self)
       end
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `hash'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `public_send'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `create_and_add_element'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:160:in `add_to_xml'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:226:in `block (2 levels) in build_unordered_element'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:214:in `each'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:214:in `block in build_unordered_element'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:45:in `block in create_and_add_element'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:68:in `public_send'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:68:in `method_missing'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `public_send'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:43:in `create_and_add_element'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:203:in `build_unordered_element'
     # ./lib/lutaml/model/xml_adapter/xml_document.rb:125:in `build_element'
     # ./lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:23:in `block in to_xml'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:9:in `block in build'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:8:in `new'
     # ./lib/lutaml/model/xml_adapter/builder/nokogiri.rb:8:in `build'
     # ./lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:16:in `to_xml'
     # ./lib/lutaml/model/serialize.rb:542:in `public_send'
     # ./lib/lutaml/model/serialize.rb:542:in `block (2 levels) in <module:Serialize>'
     # ./spec/lutaml/model/type_spec.rb:245:in `block (4 levels) in <top (required)>'

  8) Lutaml::Model::Type Type Usage in Models Serialization correctly deserializes from XML
     Failure/Error: expect(deserialized.hash_value).to eq({ "key" => "value" })
     
       expected: {"key"=>"value"}
            got: {"key"=>{"text"=>"value"}, "text"=>["\n    ", "\n  "]}
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,3 @@
       -"key" => "value",
       +"key" => {"text"=>"value"},
       +"text" => ["\n    ", "\n  "],
       
     # ./spec/lutaml/model/type_spec.rb:274:in `block (4 levels) in <top (required)>'

  9) Person serializes to YAML
     Failure/Error: expect(model.to_yaml).to eq(attributes_yaml.to_yaml)
     
       expected: "---\nfirstName: John\nlastName: Doe\nage: 30\nheight: 5.9\nbirthdate: '1990-01-01'\nlastLogin: '2023-06-08T10:00:00+00:00'\nwakeupTime: '07:00:00'\nactive: true\n"
            got: "---\nfirstName: John\nlastName: Doe\nage: 30\nheight: 5.9\nbirthdate: 1990-01-01\nlastLogin: '2023-06-08T10:00:00+00:00'\nwakeupTime: '07:00:00'\nactive: true\n"
     
       (compared using ==)
     
       Diff:
       @@ -3,7 +3,7 @@
        lastName: Doe
        age: 30
        height: 5.9
       -birthdate: '1990-01-01'
       +birthdate: 1990-01-01
        lastLogin: '2023-06-08T10:00:00+00:00'
        wakeupTime: '07:00:00'
        active: true
       
     # ./spec/person_spec.rb:125:in `block (2 levels) in <top (required)>'

Finished in 0.10141 seconds (files took 0.21986 seconds to load)
532 examples, 9 failures, 42 pending

Failed examples:

rspec ./spec/lutaml/model/type/date_spec.rb:28 # Lutaml::Model::Type::Date.cast with DateTime object is expected to eq #<Date: 2024-01-01 ((2460311j,0s,0n),+0s,2299161j)>
rspec ./spec/lutaml/model/type/hash_spec.rb:20 # Lutaml::Model::Type::Hash.cast filters out text keys from nested hashes
rspec ./spec/lutaml/model/type/integer_spec.rb:40 # Lutaml::Model::Type::Integer.cast with float string is expected to eq 123
rspec ./spec/lutaml/model/type/integer_spec.rb:46 # Lutaml::Model::Type::Integer.cast with exponential notation is expected to eq 123
rspec ./spec/lutaml/model/type/integer_spec.rb:52 # Lutaml::Model::Type::Integer.cast with negative exponential notation is expected to eq -123
rspec ./spec/lutaml/model/type/integer_spec.rb:58 # Lutaml::Model::Type::Integer.cast with string containing leading zeros is expected to eq 123
rspec ./spec/lutaml/model/type_spec.rb:228 # Lutaml::Model::Type Type Usage in Models Serialization correctly serializes to XML
rspec ./spec/lutaml/model/type_spec.rb:248 # Lutaml::Model::Type Type Usage in Models Serialization correctly deserializes from XML
rspec ./spec/person_spec.rb:124 # Person serializes to YAML
```

**Comment by HassanAkbar** [comment]
@ronaldtse All specs are fixed now.

**Pull request merged**
