### PR TITLE
Add comparable feature

### PR DESCRIPTION
**Pull request by ronaldtse**
Lutaml::Model objects can be compared with each other and a diff tree drawn out.

Further work is needed in this PR for:
1. One test failure right now due to the need to implement a `#validate` method on the Model object, which will call `#validate` on its attributes in order to trigger Enum validation errors.
2. Make the CLI work, see #18

### CODE REVIEW

**Comment by ronaldtse** [comment]
@HassanAkbar can you please help work on this? Thanks!

**Comment by HassanAkbar** [comment]
> @HassanAkbar can you please help work on this? Thanks!

@ronaldtse Sure, looking into it.

**Comment by ronaldtse** [comment]
Merging the comparable part first. the CLI will be a separate issue, FYI @HassanAkbar .

**Comment by ronaldtse** [comment]
The remaining work is to provide a CLI for Lutaml::Model objects (YAML, XML, etc), see #18 .

**Pull request merged**
