### PR TITLE
fix: test cases for genericode repo

### PR DESCRIPTION
**Pull request by HassanAkbar**
For fixing https://github.com/lutaml/genericode/pull/13

### CODE REVIEW

**Comment by ronaldtse** [comment]
The “of_” methods and “as_” methods are used internally to build the hash for the “to_” methods. We should either use them internally with the new “of_” methods or just give the user another way to achieve what they need, which is just to build/parse the serialized item?

ie. We should not need to maintain additional “of_” methods if they are not needed internally.

**Comment by HassanAkbar** [comment]
> We should not need to maintain additional “of_” methods if they are not needed internally.

@ronaldtse Currently I am trying to pass all the test cases for `genericode` repo, once all the tests are green I will refactor the methods and the code in `genricode` repo to match `lutaml-model` style.

**Comment by HassanAkbar** [comment]
@ronaldtse this will fix all the test cases for the `genericode` repo.

**Review by ronaldtse — APPROVED** [review]
Thank you @HassanAkbar !

**Comment by ronaldtse** [comment]
@HassanAkbar since this PR added a number of methods like `of_*`, if they are meant for user use, we should get them documented. Thanks.

**Pull request merged**
