### PR TITLE
feat: add schemaLocation if present

### LINKED ISSUE #64: Automatically support `xsi:schemaLocation` for all XML elements
`schemaLocation` is a necessary step in XML files that use XSD, so we must support it somehow. I don't know if we should supported it in the user gem or lutaml-model level. Perhaps the latter makes more sense?

The latter makes more sense because `xsi:schemaLocation` can happen on any XML element. It is not possible to make the user add this namespace and attribute to every element they define.

Ping @HassanAkbar .

_Originally posted by @ronaldtse in https://github.com/lutaml/ogc-gml/issues/9#issuecomment-2321031514_

### PR DESCRIPTION
**Pull request by HassanAkbar**
Automatically support `xsi:schemaLocation` for all XML elements if present in XML

closes #64

### CODE REVIEW

**Review by ronaldtse — CHANGES_REQUESTED** [review]
@HassanAkbar I've added a README and some specs to test for multiple schemaLocations. As you can see [here](https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256100(v=vs.100)), there could be multiple schemaLocations, and we need to support that. Can you help revise and update the feature/specs?

**Comment by HassanAkbar** [comment]
@ronaldtse I've updated the code according to the specs you added, I just changed how the `schemaLocation` object was being created in the [test cases](https://github.com/lutaml/lutaml-model/pull/68/files#diff-e0ab91e15f4e7c717cc1ffcf56114921f32e73f879878e507a01ad6dfaeacff2R177) that you added. 
Can you check that and let me know if that is correct or do I need to change that? Thanks

**Comment by ronaldtse** [comment]
Somehow this is failing...

```ruby
class Ceramic < Lutaml::Model::Serializable
  attribute :type, :string
  attribute :glaze, :string
  attribute :color, :string

  xml do
    root 'Ceramic'
    namespace 'http://example.com/ceramic', 'cera'
    map_element 'Type', to: :type, namespace: :inherit
    map_element 'Glaze', to: :glaze
    map_attribute 'color', to: :color, namespace: 'http://example.com/color', prefix: 'clr'
  end
end

xml = <<~HERE
<cera:Ceramic
  xmlns:cera="http://example.com/ceramic"
  xmlns:clr="http://example.com/color"
  xsi:schemaLocation=
    "http://example.com/ceramic http://example.com/ceramic.xsd
     http://example.com/color http://example.com/color.xsd"
  clr:color="navy-blue">
  <cera:Type>Porcelain</cera:Type>
  <Glaze>Clear</Glaze>
</cera:Ceramic>
HERE

Ceramic.from_xml(xml)
```

@HassanAkbar any idea?

**Comment by ronaldtse** [comment]
Actually it works! Sorry!!

**Comment by ronaldtse** [comment]
No actually it doesn't?

```ruby
$ bundle console
# ...
require_relative "../lib/lutaml/model/xml_adapter/nokogiri_adapter"
Lutaml::Model::Config.configure do |config|
  config.xml_adapter_type = :nokogiri
end

class Ceramic < Lutaml::Model::Serializable
  attribute :type, :string
  attribute :glaze, :string
  attribute :color, :string

  xml do
    root 'Ceramic'
    namespace 'http://example.com/ceramic', 'cera'
    map_element 'Type', to: :type, namespace: :inherit
    map_element 'Glaze', to: :glaze
    map_attribute 'color', to: :color, namespace: 'http://example.com/color', prefix: 'clr'
  end
end

xml_content = <<~HERE
<cera:Ceramic
  xmlns:cera="http://example.com/ceramic"
  xmlns:clr="http://example.com/color"
  xsi:schemaLocation=
    "http://example.com/ceramic http://example.com/ceramic.xsd
     http://example.com/color http://example.com/color.xsd"
  clr:color="navy-blue">
  <cera:Type>Porcelain</cera:Type>
  <Glaze>Clear</Glaze>
</cera:Ceramic>
HERE

a = Ceramic.from_xml(xml_content)
a.schema_location
# => nil
```

**Comment by ronaldtse** [comment]
> @ronaldtse I've updated the code according to the specs you added, I just changed how the `schemaLocation` object was being created in the [test cases](https://github.com/lutaml/lutaml-model/pull/68/files#diff-e0ab91e15f4e7c717cc1ffcf56114921f32e73f879878e507a01ad6dfaeacff2R177) that you added. Can you check that and let me know if that is correct or do I need to change that? Thanks

The tests are just illustrative but the way it works seems fine to me.

**Comment by HassanAkbar** [comment]
> No actually it doesn't?
> 
> ```ruby
> $ bundle console
> # ...
> require_relative "../lib/lutaml/model/xml_adapter/nokogiri_adapter"
> Lutaml::Model::Config.configure do |config|
>   config.xml_adapter_type = :nokogiri
> end
> 
> class Ceramic < Lutaml::Model::Serializable
>   attribute :type, :string
>   attribute :glaze, :string
>   attribute :color, :string
> 
>   xml do
>     root 'Ceramic'
>     namespace 'http://example.com/ceramic', 'cera'
>     map_element 'Type', to: :type, namespace: :inherit
>     map_element 'Glaze', to: :glaze
>     map_attribute 'color', to: :color, namespace: 'http://example.com/color', prefix: 'clr'
>   end
> end
> 
> xml_content = <<~HERE
> <cera:Ceramic
>   xmlns:cera="http://example.com/ceramic"
>   xmlns:clr="http://example.com/color"
>   xsi:schemaLocation=
>     "http://example.com/ceramic http://example.com/ceramic.xsd
>      http://example.com/color http://example.com/color.xsd"
>   clr:color="navy-blue">
>   <cera:Type>Porcelain</cera:Type>
>   <Glaze>Clear</Glaze>
> </cera:Ceramic>
> HERE
> 
> a = Ceramic.from_xml(xml_content)
> a.schema_location
> # => nil
> ```

@ronaldtse This is happening because the `xmlns:xsi` is not defined and nokogiri is treating `xis:schemaLocation` as a attribute name and not `xsi` as prefix and `schemaLocation` as attribute name which we are expecting.

I'll update the code to handle this scenario.

**Comment by ronaldtse** [comment]
Ahh @HassanAkbar yes you are right. We need to define the namespace xsi first. My example XML was mistaken. It’s fine then.

**Comment by ronaldtse** [comment]
This is all good, I've tested it with the (updated) sample in the README. Merging once tests pass.

**Pull request merged**
