### PR TITLE
fix: failing test cases

### PR DESCRIPTION
**Pull request by HassanAkbar**
Fixing failing test cases

related to #8

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thank you @HassanAkbar for the wonderful work. Feel free to merge when ready!

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar ! We should release a new version to indicate the gem now works!

**Comment by HassanAkbar** [comment]
@ronaldtse Just checked the release workflow that you ran and I think the `RUBYGEMS_API_KEY` is not setup for this repo.

**Comment by ronaldtse** [comment]
@HassanAkbar I've updated the API key.

**Comment by ronaldtse** [comment]
@HassanAkbar the gem is now released. The previous problem was due to a mistake in the name of the security tokens fixed in #13 .

**Comment by HassanAkbar** [comment]
> @HassanAkbar the gem is now released. The previous problem was due to a mistake in the name of the security tokens fixed in #13 .

Awesome. Thanks @ronaldtse .

**Pull request merged**
