### PR TITLE
feat: adding enum methods to serializeable

### LINKED ISSUE #201: add enum methods
Glossarist uses enum methods, and multiple values for enum are also supported, so we need to add that to the lutaml model as well.

We can make the values an enum and use `collection: true` to see if they contain multiple values. For example for the given snippet

```ruby
class GrammarInfo
  attribute :number, values: %w[singular dual plural], collection: true
end
```

### Current behavior:

The above snippet does not parse multiple values for number i.e `number = %w[dual plural]

### Expected behavior:

The above snippet should parse multiple values for number i'e `number = %w[dual plural]

blocking -> https://github.com/glossarist/glossarist-ruby/issues/107

### PR DESCRIPTION
**Pull request by HassanAkbar**
Add enum methods to serializable

fixes #201

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Let's add a section in the README about using this use case, i.e. `values: [...]` with `collection: true` (is this correct?).

**Comment by HassanAkbar** [comment]
> Let's add a section in the README about using this use case, i.e. `values: [...]` with `collection: true` (is this correct?).

@ronaldtse Yes that is correct and some convenience methods are added for enum values, I'll update the readme after finalizing this PR.

**Comment by HassanAkbar** [comment]
> @HassanAkbar is this completed? Could you please help merge since it is blocking another task at [metanorma/suma#18](https://github.com/metanorma/suma/pull/18) ? Thanks!

@ronaldtse Sure, I'll finalize and merge this in a bit.

**Comment by HassanAkbar** [comment]
@ronaldtse Version `0.4.0` released for this.

**Pull request merged**
