### PR TITLE
from_yaml does not deal with collection attributes

### LINKED ISSUE #74: from_yaml does not deal with collection attributes
https://github.com/metanorma/metanorma/pull/403

The issue I am now running into is:

lib/metanorma/collection/config/manifest.rb
```ruby
class Manifest < ::Lutaml::Model::Serializable
  # ...
  attribute :entry, Manifest, collection: true
  # ....

  yaml do
    map "docref", to: :entry, with: { from: :docref_from_yaml, to: :nop_to_yaml }
  end
end

def docref_from_yaml(model, value)
  model.entry = Manifest.from_yaml(value.to_yaml)
end
```

lutaml-model-0.3.8/lib/lutaml/model/serialize.rb

```ruby
define_method(:"from_#{format}") do |data|
  adapter = Lutaml::Model::Config.send(:"#{format}_adapter")
  doc = adapter.parse(data)
  public_send(:"of_#{format}", doc.to_h)
end

data = [{"level"=>"subcollection", "title"=>"Standards", "docref"=>[{"fileref"=>"../collection/dummy.xml", "identifier"=>"ISO 44001", "index"=>true}, {"fileref"=>"dummy.1.xml", "identifier"=>"ISO 44002", "index"=>false}, {"fileref"=>"dummy.xml", "identifier"=>"ISO 44003"}]}]
```

from_yaml is assuming that it will always find a Hash. If the element is a collection, it will be an array.

This is a foundational bug....

### PR DESCRIPTION
**Pull request by HassanAkbar**
Fixing test cases for https://github.com/metanorma/metanorma/pull/403

closes #74

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse I am working on fixing test cases for https://github.com/metanorma/metanorma/pull/403. 
The issue mentioned in https://github.com/lutaml/lutaml-model/issues/74 is fixed but there are some more issue here so should I fix all of these in this PR or should I open a separate PR for other issues?

**Comment by ronaldtse** [comment]
@HassanAkbar for all of these fixes we need to have corresponding specs to test them. 

It is suitable to use multiple PRs if the fixes apply to different areas.

**Comment by HassanAkbar** [comment]
@ronaldtse Got it, I'll divide this into separate PRs with corresponding specs.

**Review by ronaldtse — APPROVED** [review]
I think serialization to JSON deserves its own separate spec as well, but this is okay to merge.

**Pull request merged**
