### PR TITLE
Additional XML namespace behavior specs

### PR DESCRIPTION
**Pull request by ronaldtse**
It seems that the behavior for XML namespaces isn't always correct.

@HassanAkbar can you please help fix them (the implementation or the tests)? Thanks.

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse I have fixed the specs, can you please review this? Thanks

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar !

**Comment by ronaldtse** [comment]
Can't seem to fix the remaining Rubocop issue. Merging first.

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar !

**Pull request merged**
