### PR TITLE
Adding support for mixed content

### LINKED ISSUE #7: Make "mixed" content work like the STS gem
Extend map_content.

### PR DESCRIPTION
**Pull request by HassanAkbar**
Added support for `mixed: true` in Lutaml Model.

closes #7

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar ! Could you please help update the README? Thanks.

**Comment by HassanAkbar** [comment]
> Could you please help update the README? Thanks.

@ronaldtse Sure, I'm on it.

**Comment by HassanAkbar** [comment]
@ronaldtse I've updated the readme

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar !

**Pull request merged**
